### ISSUE TITLE
Option for Android? 

### ISSUE THREAD

**Issue by tgoldenberg** [react-native-fellowship/react-native-navbar#101]
I just noticed that if you comment out the two lines that reference StatusBarIOS, then the navbar works fine in Android. Maybe we can have a guard clause or something so that it's reusable?

**Comment by Kureev** [comment]
I think it's really strange to have an iOS navbar on Android. Does it make any sense to you?

**Comment by tgoldenberg** [comment]
@Kureev  I guess you see it differently from me, but having a navbar package makes it faster to develop, regardless of Android / iOS. Most of the community is leaning towards components that are reusable on iOS & Android, too. I haven't seen any other navbar packages out there, and none with Android support, so I don't see why you would want to limit the project....

**Comment by Kureev** [comment]
I don't want to limit this project, but it's hard to say that it's the same: it's totally different UI and UX. 
If we're talking about Android, we need to follow [toolbar](https://www.google.com/design/spec/components/toolbars.html#) and [menu](https://www.google.com/design/spec/components/menus.html) guidelines. That's gonna take a while... If you want to help with it - I'll really appreciate your help.

**Comment by niftylettuce** [comment]
Please add android

**Comment by niftylettuce** [comment]
My fork supports android now

**Comment by Kureev** [comment]
@niftylettuce with material design? Can you make a PR?

**Comment by niftylettuce** [comment]
No time at moment

**Comment by Kureev** [comment]
Working on Android version at the moment. Please, take a minute to [read a proposal](https://github.com/react-native-fellowship/react-native-navbar/issues/109) and put your opinion on it.

**Comment by Taakn** [comment]
Would be great if the component could at least work the same with Android

**Comment by yogiben** [comment]
Creating a quick fix for Android #135 

If you want to use this before it's merged, update `package.json` depencies to
`"react-native-navbar": "git://github.com/yogiben/react-native-navbar.git#master",`

**Comment by Taakn** [comment]
@yogiben thanks your quick fix works for me !

**Comment by Kureev** [comment]
Merged @yogiben's PR. Thanks, man :+1:

**Comment by Kureev** [comment]
Released `1.2.0` with #135

**Comment by Taakn** [comment]
@Kureev works well I think you can change your README.md `Customizable navbar for react-native [iOS only]` to include Android :+1:
