### ISSUE TITLE
Get rid of or document border bottom

### ISSUE THREAD

**Issue by niftylettuce** [react-native-fellowship/react-native-navbar#102]
This was super frustrating to debug why some 0.5 width bar was showing

**Comment by niftylettuce** [comment]
My fork gets rid of this

**Comment by puzzfuzz** [comment]
+1 not sure what this is here for and why it's not configurable

**Comment by nodkrot** [comment]
+1

**Comment by Kureev** [comment]
Done in `1.0.6`
