### ISSUE TITLE
How do I use an image as a background for the navbar? 

### ISSUE THREAD

**Issue by sankhadeeproy007** [react-native-fellowship/react-native-navbar#106]
Is there any way I can use as the background for the navbar? If so, what are the css properties I should use? I did try but couldn't quite get the properties right. 
![screen shot 2015-11-06 at 5 36 03 pm](https://cloud.githubusercontent.com/assets/10998047/10996653/01f3628a-84ad-11e5-97fa-4c7f3d6281e1.png)

**Comment by Kureev** [comment]
Well, we don't expose any API for this case yet. As a workaround, you can wrap navbar component with `tintColor="rgba(0, 0, 0, 0)"` into high-order component with background you want. Please, let me know if it works.

**Comment by jadsonlourenco** [comment]
Can be a prop like **customBackground**, it will render a component not only an Image, because some times we need more things, like an image with blur effect, etc. So:

```
<View style={[styles.navBarContainer, customTintColor, {overflow: 'hidden'}]}>
  <BackgroundComponent style={{position: 'absolute', top: 0, left: 0}} />
  {statusBar}
  <View style={[styles.navBar, this.props.style, ]}>
    {this.getTitleElement(this.props.title)}
    {this.getButtonElement(this.props.leftButton, { marginLeft: 8, })}
    {this.getButtonElement(this.props.rightButton, { marginRight: 8, })}
  </View>
</View>
```
Look that "BackgroundComponent" has the "absolute" position and the navBarContainer `overflow: 'hidden'`. Just an idea.

**Comment by Kureev** [comment]
@jadsonlourenco if you'll scale out the problem, it's more about how users can customize navbar if they want to. That's why I have a [proposal](https://github.com/react-native-fellowship/react-native-navbar/issues/109) I'm working on right now. I want to provide a simple building blocks to people who want to build their own navbar. In the meanwhile, I'd like to find a workaround for this.

**Comment by jadsonlourenco** [comment]
@Kureev well to be simple for now is like I suggest, but with an Image component, will be like `backgroundImage` to pass the image path, and accept all <Image /> props.

**Comment by Kureev** [comment]
Well, that's very close to what I've proposed above: just use Image as a container for the Navbar and set Navbar background color to transparent :wink:

**Comment by jadsonlourenco** [comment]
Yes, is true, sorry! :+1:
