### ISSUE TITLE
How to change background color fully?

### ISSUE THREAD

**Issue by nodkrot** [react-native-fellowship/react-native-navbar#113]
I have this:
```jsx
<NavigationBar
    style={{ backgroundColor: 'red' }}
    title={titleConfig}
    rightButton={rightButtonConfig}
    leftButton={leftButtonConfig} />
```
and this is what it's giving me 
<img width="320" alt="screen shot 2015-11-21 at 3 59 22 pm" src="https://cloud.githubusercontent.com/assets/5076567/11320527/e847d826-9068-11e5-850d-018f23383707.png">

How can I make everything one color?

**Comment by adamterlson** [comment]
Use `tintColor: 'red'` instead of the style.

**Comment by Kureev** [comment]
Yep, @adamterlson is right, you should use `tintColor` property instead. Take a look on [public API](https://github.com/react-native-fellowship/react-native-navbar#api) for this component

**Comment by nodkrot** [comment]
Got it thx!
