### ISSUE TITLE
data.isReactElement has been deprecated from RN 0.13

### ISSUE THREAD

**Issue by steveleec** [react-native-fellowship/react-native-navbar#120]
Inside index.js that belongs to react-native-navbar, there is an if statement that is not being triggered when a react component is passed through "leftButton" prop. 
At any given time, data._isReactElement is not recognized. There is chance that it got deprecated after RN 0.13 (https://github.com/facebook/react/issues/3220 and https://github.com/facebook/react/issues/3473).

```javascript
getButtonElement(data = {}, style) {
    if (data._isReactElement) {
      return <View style={styles.navBarButton}>{data}</View>;
    }
//...
```
Any workaround for this?

**Comment by steveleec** [comment]
This is the way I fixed.
I wen to index.js that belongs to react-native-navbar to change it to this:

```javascript
//from
getButtonElement(data = {}, style) {
    console.log('data inside module', data);
    if (data._isReactElement ){
      return <View style={styles.navBarButton}>{data}</View>;
    }
//
getButtonElement(data = {}, style) {
    console.log('data inside module', data);
    if (!!data.props ){
      return <View style={styles.navBarButton}>{data}</View>;
    }
```
and
```javascript
// from 
getTitleElement(data) {
    if (data._isReactElement) {
      return <View style={styles.customTitle}>{data}</View>;
    }
//to
getTitleElement(data) {
    if (!!data.props) {
      return <View style={styles.customTitle}>{data}</View>;
    }
```
However, to make it work, inside
```javascript
<NavigationBar
          leftButton={
            <TouchableOpacity style={styles.buttonNavBar} onPress={()=> this.props.navigator.pop()}>
              <Image
                source={require('../img/back-icon.png')}
                style={[{ width: 15, height: 15}]}/>
            </TouchableOpacity>
          }/>
```
I have to define the component directly to leftButton and not creating a class Component because the later one is gotten as a function.

**Comment by Kureev** [comment]
LGTM, can you compose a PR?

**Comment by grabbou** [comment]
Fixed in https://github.com/react-native-fellowship/react-native-navbar/pull/121
