### ISSUE TITLE
RN 0.16, Invariant Violation error

### ISSUE THREAD

**Issue by linoleum00** [react-native-fellowship/react-native-navbar#122]
When trying to reproduce the readme example, I have:

var NavigationBar = require('react-native-navbar');
...
render() {
        var rightButtonConfig = {
            title: 'Next',
            handler: function onNext() {
                alert('hello!');
            }
        };

        var titleConfig = {
            title: 'Hello, world',
        };
        return (

            <View style={{ flex: 1, }}>
                <NavigationBar
                    title={titleConfig}
                    rightButton={rightButtonConfig} />
            </View>
        );
    }
When I try to run the example I get this error:

Unhandled JS Exception: Invariant Violation: Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `AwesomeProject`.

Please help me with this

Thanks

**Comment by linoleum00** [comment]
dsibiski [5:11 PM] 
@linoleum00: Make sure you are using `module.exports` in the files you are importing
dsibiski [5:18 PM] 
ok, because I went through all of that a couple days ago…every single file needs to have “module.exports” and not rely on “export default”…if one in the chain doesn’t have it you will get that exact error

I had this conversation the other and he told me to use module.exports, and when I looked into your index.js I saw the export default line, I don't know if this is the cause but it is worth looking at it

**Comment by grabbou** [comment]
The `export default` is ES6 module system that is, thanks to Babel equivalent to `module.exports` you can find in Node.js so that's not the case.

**Comment by linoleum00** [comment]
Awesome, thanks!

**Comment by achang28** [comment]
I, too am having same issue.  Currently running RN v0.16.0, Xcode 7.2, IOS 8.1, and react-native-navbar v1.1.1

**Comment by vincentbello** [comment]
Hey, any word on this? I'm having the same issue.

**Comment by Kureev** [comment]
Yes, we need to change `dependencies` in package.json to `peerDependencies`.

**Comment by linoleum00** [comment]
U was using 0.16 when the error happened just in case, I forgot to mention it

**Comment by vincentbello** [comment]
Awesome, thanks for your quick response.

**Comment by linoleum00** [comment]
So, I am still having this issue, and what I did is, on the index.js I removed the export default and I added in the last line module.exports= NavigationBar; and it is working now. So please take a look at that

**Comment by Kureev** [comment]
I'm rounding off with `side-menu` now, then I'm going to take a deep look into `navbar` component. Please, be patient :wink:

**Comment by linoleum00** [comment]
great! thanks

**Comment by sankhadeeproy007** [comment]
I have the same problem. rn: 0.17, rn-navbar: 1.1.2

**Comment by Kureev** [comment]
Solved in `1.1.4`

**Comment by sankhadeeproy007** [comment]
Hey @Kureev, I know it's a pretty stupid question to ask, but somehow I'm getting `Can't find variable: NavigationBar` error. I just updated to `1.1.4` and can't seem to get it to work. I had however used previous versions successfully. Any idea where I went wrong?

**Comment by Kureev** [comment]
Hey @sankhadeeproy007! That looks super weird :open_mouth:. The only thing we changed - is a way we export a class, it shouldn't be a problem.

**Comment by sankhadeeproy007** [comment]
![screen shot 2015-12-29 at 12 36 32 pm](https://cloud.githubusercontent.com/assets/10998047/12030705/d81aac66-ae28-11e5-891a-a130543ded26.png)
This is the error I'm getting. I tried removing node_modules and did a fresh npm install, still it didn't help. Can you help me?
