### ISSUE TITLE
Warning: Invalid prop 'rightButton' supplied to 'NavigationBar'.

### ISSUE THREAD

**Issue by deju** [react-native-fellowship/react-native-navbar#133]
I use react-native-navbar like this:

    var rightBtnConfig = {
      title: '历史记录',
      style: Styles.navbarBtn,
      handler: function(){
        nav.push({
          id: 'history',
        });
      }
    };

    <NavigatorBar title={titleConfig} leftButton={leftBtnConfig} rightButton={rightBtnConfig} style={Styles.navbar}  />

But i got the warning. If i remove style prop in variable rightBtnConfig and the warning will disapper.

So if i want to custom the style, like font-size, how should i do?

**Comment by Kureev** [comment]
你好!

If I understood your problem correctly, then new `1.1.7` release will help you :wink:

**Comment by deju** [comment]
@Kureev  Thank you! And now is ok. There may be other ways to set FontSize. (FontSize prop can not set in the Nav) Should i custom a component like the demo you give us?

**Comment by Kureev** [comment]
Yeah, currently there's no way to change a font size. I'd recommend you to make your own component for this case. You can [take a look on default one here](https://github.com/react-native-fellowship/react-native-navbar/blob/master/NavbarButton.js)

**Comment by deju** [comment]
@Kureev OK, Thank you. You know chinaese? :+1:

**Comment by Kureev** [comment]
@deju You're welcome. Nope, unfortunately I don't :disappointed: But Google translate knows it pretty well :wink:

**Comment by deju** [comment]
@Kureev Google is always awesome!
