### ISSUE TITLE
A `5px` white stripe shown if using `tintColor` to change the BG color of navBarContainer

### ISSUE THREAD

**Issue by cowfox** [react-native-fellowship/react-native-navbar#141]
Here is the color I set: 

```
tintColor: '#05A5D1',
```
And seems that the **5px** `paddingBottom` added inside the source code makes this **5px** stripe shown. 

```
// styles.js
navBarContainer: {
    backgroundColor: 'white',
    paddingBottom: 5,
  },
```

![screen shot 2016-02-28 at 9 19 09 pm](https://cloud.githubusercontent.com/assets/4998114/13384199/6c71933a-de61-11e5-89d0-bc4293e72584.png)

**Comment by Kureev** [comment]
Fixed in `1.2.2`
