### ISSUE TITLE
Status bar hidden when rotating iPhone

### ISSUE THREAD

**Issue by Mokto** [react-native-fellowship/react-native-navbar#143]
Hi,

My status bar works fine but when I rotate to lanscape mode from portrait, it disappears.
It's working when app start from landscape and i rotate to portrait.

```javascript
<NavigationBar
          title={{title: title, tintColor: "white"}}
          tintColor="#E74C3C"
          statusBar={{style: 'light-content', hidden: false}}
          leftButton={this.getLeftButton()}
          rightButton={this.getRightButtons()}
        />
```

![img_0078](https://cloud.githubusercontent.com/assets/5103928/13623750/c65ae2fe-e576-11e5-83ad-9a5ce6797342.PNG)
![img_0079](https://cloud.githubusercontent.com/assets/5103928/13623751/c66b01ca-e576-11e5-95ad-b975948eab6f.PNG)

Have you got any idea ?

Please tell me if you need anything else.

**Comment by Kureev** [comment]
Wow, that's super weird. Can you verify that it happens only when you use a navbar?

**Comment by Mokto** [comment]
You are right, sorry.

Having this issue with react-native-router-flux too.

Thanks !

**Comment by booboothefool** [comment]
@Mokto 

Hey man, I'm also using react-native-router-flux. I can't seem to figure out what causes this, but my statusbar will just randomly disappear sometimes. Did you ever find out any leads?
