### ISSUE TITLE
Status bar hide not working on android

### ISSUE THREAD

**Issue by npomfret** [react-native-fellowship/react-native-navbar#144]
There's a big gap above the nav-bar on android.  The only way to remove it is to set 

`
statusBar = {hidden: true}
`
Which I guess is supposed to hide the status bar, but on Android doesn't - it just removed the unwanted gap.

**Comment by Kureev** [comment]
I think I'll remove this flag in the next version. Usually you want to setup this setting once for your application lifecycle, and it's a way easier to do using a native platform settings.

**Comment by npomfret** [comment]
Will you also fix it so that it works in Android?

**Comment by Kureev** [comment]
Should be fixed in `1.4.0`.
