### ISSUE TITLE
The title is not align center in vertical.

### ISSUE THREAD

**Issue by deju** [react-native-fellowship/react-native-navbar#145]
![2016-03-14 2 12 03](https://cloud.githubusercontent.com/assets/1439939/13736372/f33b0c96-e9ee-11e5-9b8f-f676201c9038.png)

The title "Test" is not align center in vertical. How do i fix?

**Comment by deju** [comment]
nav version: 1.2.2
RN version: 0.20.0

**Comment by spietrek** [comment]
Here are the changes i made to styles.js to center the buttons and title vertically.

const NAV_BAR_HEIGHT = 44;
const STATUS_BAR_HEIGHT = 20;
const NAV_HEIGHT = NAV_BAR_HEIGHT + STATUS_BAR_HEIGHT;

module.exports = {
  navBarContainer: {
    backgroundColor: 'white',
  },
  statusBar: {
    height: STATUS_BAR_HEIGHT,
  },
  navBar: {
    height: NAV_BAR_HEIGHT,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customTitle: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 14,
    alignItems: 'center',
  },
  navBarButton: {
    marginTop: 10,
  },
  navBarButtonText: {
    fontSize: 17,
    letterSpacing: 0.5,
    marginTop: 10,
  },
  navBarTitleText: {
    fontSize: 17,
    letterSpacing: 0.5,
    color: '#333',
    fontWeight: '500',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 14,
    textAlign: 'center',
  },
};

**Comment by deju** [comment]
@spietrek  Thank you. I changed the styles for chinese.

const NAV_BAR_HEIGHT = 44;
const STATUS_BAR_HEIGHT = 20;
const NAV_HEIGHT = NAV_BAR_HEIGHT + STATUS_BAR_HEIGHT;

module.exports = {
  navBarContainer: {
    backgroundColor: 'white',
  },
  statusBar: {
    height: STATUS_BAR_HEIGHT,
  },
  navBar: {
    height: NAV_BAR_HEIGHT,
    flexDirection: 'row',
    justifyContent: 'space-between',
  },
  customTitle: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 14, 
    alignItems: 'center',
  },
  navBarButton: {
    marginTop: 12, 
  },
  navBarButtonText: {
    fontSize: 17,
    letterSpacing: 0.5,
    marginTop: 12, 
  },
  navBarTitleText: {
    fontSize: 17,
    letterSpacing: 0.5,
    color: '#333',
    fontWeight: '500',
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 14, 
    textAlign: 'center',
  },
};


This works for me.

**Comment by xing-zheng** [comment]
I have a ultimate solution for this problem, regardless language or font size of the title. 
please review the PR #151

**Comment by holyxiaoxin** [comment]
I have problems with title not centering too. I managed to center left and right button. But title seems to take on a different styling from the other 2 since I cannot apply the same styles on all 3 of them to arrive at similar results. I have observed that using a custom component for title restricts the position of it.

Please review @xing-zheng xing-zheng's PR. Thanks (:
