### ISSUE TITLE
Update `customizeStatusBar` to match new StatusBar API

### ISSUE THREAD

**Issue by gooooer** [react-native-fellowship/react-native-navbar#148]
In version 1.3+ you've replaced `StatusBarIOS` with `StatusBar`. But `StatusBar` API is different from `StatusBarIOS` thus all calls to `StatusBar` in `customizeStatusBar` aren't valid anymore and this component fails to load.

Please update according to new API.

**Comment by Kureev** [comment]
They've been updated in the `1.3.1`.
