### ISSUE TITLE
StatusBar.setStatusBar is not a function

### ISSUE THREAD

**Issue by SpaceRangerWes** [react-native-fellowship/react-native-navbar#150]
This is the same issue as #147 however I am running react-native: 0.21.0 and have version 1.3 of navbar. Are you still suggesting a downgrade?

**Comment by skizzo** [comment]
+1, updating to react-native 0.21.0 doesn't help.

**Comment by Kureev** [comment]
`1.3.0` is broken. This commit fixes the problem https://github.com/react-native-fellowship/react-native-navbar/commit/b86d3fc9308805fb62314424039cf109ee46f674. It has been released 2 days ago.

**Comment by TheWildHorse** [comment]
I couldn't update to 1.3.1 via NPM, but when I manually installed it to my project, the fix still doesn't solve the issue. It just says that barStyle is not a function. :/

**Comment by Kureev** [comment]
Just published `1.3.1` and `1.3.2` to npm. `1.3.2` should fix this issue. Please, check if that works for you

**Comment by TheWildHorse** [comment]
Sure does work! Cheers!
