### ISSUE TITLE
StatusBar.setBarStyle is undefined ( index.js @36:0 )

### ISSUE THREAD

**Issue by sarovin** [react-native-fellowship/react-native-navbar#152]
I followed your Readme for add NavigationBar but i have this error...

![schermata 2016-03-21 alle 12 27 18](https://cloud.githubusercontent.com/assets/5980398/13917435/f46a9c68-ef60-11e5-8b8a-525e8f000991.png)

**Comment by Kureev** [comment]
That should be fixed already, try to update plugin to the latest version, please
