### ISSUE TITLE
Android take some space at top

### ISSUE THREAD

**Issue by radiegtya** [react-native-fellowship/react-native-navbar#153]
I am just using standard basic implementation just like example. On iOS its working just fine, but on android it take some space at top. Please help.

<img width="499" alt="navbar-going-down" src="https://cloud.githubusercontent.com/assets/2161622/13951196/ef5b7222-f061-11e5-9b74-28ca78a6660d.png">

**Comment by Kureev** [comment]
Fixed in `1.4.0`

**Comment by radiegtya** [comment]
cool! it's working. Thanks a lot @Kureev

**Comment by Kureev** [comment]
Thanks for reporting this bug :+1:

**Comment by radiegtya** [comment]
You are welcome
