### ISSUE TITLE
Trying to set title property with props fail!

### ISSUE THREAD

**Issue by rafaelv90** [react-native-fellowship/react-native-navbar#156]
I created a `CustomNavbar` component which encapsules the react-native-navbar `NavigationBar.`
I pass the title through `props`, but it seems that when the object is being mounted the value is `undefined` and then changes to the correct value, but the `NavigationBar` don't update.

<img width="373" alt="screen shot 2016-03-30 at 6 12 12 pm" src="https://cloud.githubusercontent.com/assets/1039403/14157762/f6cb6886-f6a2-11e5-8f59-e16deeac881a.png">
This `console.log(...)` prints `undefined` and my correct title right after. Any clue on this?

**Comment by Kureev** [comment]
I'm afraid I can't do anything without looking at your source code.
It also seems to be a question for [StackOverflow](http://stackoverflow.com/questions/tagged/react-native), not for a navbar repo.
