### ISSUE TITLE
Hiding or Customizing NavigationBar ?

### ISSUE THREAD

**Issue by EugeneLiang** [react-native-fellowship/react-native-navbar#166]
Hi good day, 

I was wondering if there's an API to hide the `NavigationBar` ?
If not is there any way to pass a `View` element so that we can customize the contents of `NavigationBar`? 

In particular, I'm looking to create a text input field in place of the normal `NavigationBar`

Cheers.

**Comment by Kureev** [comment]
> I was wondering if there's an API to hide the NavigationBar ?

You can just make a conditional render of navbar component.

> If not is there any way to pass a View element so that we can customize the contents of `NavigationBar`?

Currently it's a bit tricky. I have some plans to rework this component to make it composable, but have no time to do it (you may check a branch - https://github.com/react-native-fellowship/react-native-navbar/tree/feature/new-navbar). 

> In particular, I'm looking to create a text input field in place of the normal NavigationBar

Seems it would be easier to make a custom navbar by yourself in this case.
