### ISSUE TITLE
Naming collision with https://github.com/malkomalko/react-native-navbar

### ISSUE THREAD

**Issue by itinance** [react-native-fellowship/react-native-navbar#172]
When installing this package with

`npm i react-native-navbar --save`

npm will install your older iOS-only package [https://github.com/malkomalko/react-native-navbar](https://github.com/malkomalko/react-native-navbar) instead of this one here [https://github.com/react-native-fellowship/react-native-navbar/issues/new](https://github.com/react-native-fellowship/react-native-navbar/issues/new)

```
$ npm list| grep navbar
├── react-native-navbar@1.5.0
│ ├── react-native-navbar@1.1.7 (git://github.com/malkomalko/react-native-navbar.git#fe3d9ed0c717e5304188e22f86ff63f0e029919f)
```

$ npm -v
3.8.9

**Comment by Nice2Me** [comment]
me too.

who can help me ?

**Comment by Kureev** [comment]
Hey guys,

- it's not mine. 
- it seems that something else (other dependency of your project) use @malkomalko's package.

**Comment by Kureev** [comment]
I bet if you do `npm list --depth=0 | grep navbar`, you'll see only fellowship's one
