### ISSUE TITLE
scrollsToTop doesn't work

### ISSUE THREAD

**Issue by mikedizon** [react-native-fellowship/react-native-navbar#85]
When tapping the navbar, the scroll view doesn't move back to the top.

**Comment by alvinnguyen** [comment]
Tapping status bar still make scroll view move to top?

**Comment by mikedizon** [comment]
Exactly

**Comment by Kureev** [comment]
Unfortunately, `StatusBarIOS` doesn't support this behavior "by default", but I'm going to expose `onPress` event handler under `statusBar.handler`. I'll keep you posted

**Comment by grabbou** [comment]
I can't imagine good use-case for such solution (definitely not an idiomatic way for iOS users) but the handler should allow you to do so.

**Comment by Kureev** [comment]
Sorry for being late with it, but seems that it's an issue of the ScrollView, not the navbar itself. So, I'm going to close it.
