### ISSUE TITLE
iOS Styling issues

### ISSUE THREAD

**Issue by dubert** [react-native-fellowship/react-native-navbar#93]
Using this a record of things I'm working on / need to make a plan to work on:

- [ ] Navigator transitions (https://github.com/facebook/react-native/pull/2365)
- [ ] Blurred / transparent background

**Comment by Kureev** [comment]
Any update here?

**Comment by dubert** [comment]
Hey, sorry for the delay. I've been pretty slammed lately and so I haven't been able to do any work on this.

How close have you gotten to making it match the iOS nav bar?

I've done a little bit of research into hooking into the [Navigator's updateProgress](https://github.com/facebook/react-native/blob/master/Libraries/CustomComponents/Navigator/NavigatorNavigationBar.js#L140-L150), to try and handle animations, but it's pretty complex.
