### ISSUE TITLE
Hide 1px navigationBar shadow

### ISSUE THREAD

**Issue by sankhadeeproy007** [react-native-fellowship/react-native-navbar#97]
Hi, is there any way to disable the 1px dark shadow that appears when I use the navbar? I am using a transparent background and the shadow is not looking good.

**Comment by ibrens** [comment]
its a static color set in react-native-nvabar/styles.js.

easy hack // change 'borderBottomColor'

**Comment by Kureev** [comment]
Done in 1.0.6
